# Generated by Django 6.0.2 on 2026-02-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user',
            new_name='owner',
        ),
    ]
