# Generated by Django 6.0.2 on 2026-02-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumen', '0002_rename_created_by_quiz_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
