# Generated by Django 6.0.2 on 2026-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumen', '0003_programminglanguage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
