# Generated by Django 6.0.2 on 2026-02-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumen', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lumen.programminglanguage'),
        ),
    ]
