# Generated by Django 6.0.2 on 2026-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumen', '0005_alter_quiz_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
